project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: "LJL"
  twitter-card: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd 
      - Achievement.qmd
    right: 
      - icon: linkedin
        href: www.linkedin.com 

format:
  html:
    theme: 
     light: ：flatly
     dark: darkly
    css: styles.css
    toc: true

editor: visual

